source "https://rubygems.org"

gem 'citrine', git: 'git@github.com:larryloi/citrine.git', tag: "0.3.11"
gem 'chronos2', git: 'git@github.com:larryloi/chronos2.git', tag: "0.2.0"

gem 'mysql2', '>= 0.5.1'
